### ISSUE TITLE
Add BORING to whitelist

### ISSUE THREAD

**Issue by Enki-y** [kswap-finance/static#12]
## Smart Contract Address
https://www.oklink.com/okexchain/address/0x5ce01aa1528a6a0c8edecc4cee909f0a24cf54de

## Logo Link
https://imgur.com/Jo6QWz7

## Audit Report Link
https://www.certik.org/projects/boringdao

## Liquidity Pool Supply with TVL More Than 200,000 USDT
Sure.

**Comment by xbc-main** [comment]
done
