### ISSUE TITLE
Add ACMD to whitelist

### ISSUE THREAD

**Issue by ArchiProtocol** [kswap-finance/static#19]
## Smart Contract Address
0x2f8eB6F75Df534C4992Ec79d9825C5eA4b1b2A57
## Logo Link
https://photos.app.goo.gl/9jNrV9JM5m2fGQ4M9
## Audit Report Link
https://app.gitbook.com/@acmd-tothesky/s/archimedes/tutorial-1/audit-report
## Liquidity Pool Supply with TVL More Than 200,000 USDT
More Than 200,000 USDT,near 300 millions

**Comment by xbc-main** [comment]
done
