### ISSUE TITLE
Orange

### ISSUE THREAD

**Issue by catherineshek** [kswap-finance/static#2]
Introduce:
Orange builds a DeFi+NFT cross-chain bridge financial system based on OKExChain. Orange connects physical assets in the real world to provide users with various innovative applications such as depositing tokens and earning interest, lossless mining, destruction mining, NFT mining, NFT upgrades, free insurance, etc., to create a sustainable economic model and build a complete The ecological system will eventually build an Orange financial system that is cross-chain, cross-ecological, and multi-chain interoperability.

ORG contract address: 
0xb4dF33f15bd6878c6A25Ed73E088c9d89B35b2b8

Logo:
https://res.yybllz.com/org/img/org.jpg

**Comment by xbc-main** [comment]
done
