### ISSUE TITLE
Add WING to whitelist 

### ISSUE THREAD

**Issue by Yuki666666** [kswap-finance/static#20]
## Smart Contract Address
https://www.oklink.com/okexchain/tokenAddr/0x7a47ab305b8a2a3f4020d13fa9ef73cddcc0e7d4
## Logo Link
https://wing.finance/brand
## Audit Report Link
https://docs.wing.finance/#audits
## Liquidity Pool Supply with TVL More Than 200,000 USDT
Sure

**Comment by xbc-main** [comment]
done
