### ISSUE TITLE
Add NULS to whitelist

### ISSUE THREAD

**Issue by Willliang1212** [kswap-finance/static#21]
## Smart Contract Address
0x8cd6e29d3686d24d3c2018cee54621ea0f89313b
## Logo Link
https://nuls.io/wp-content/uploads/2021/04/2021_NULS_Logo_Pack.zip
## Audit Report Link
https://www.oklink.com/okexchain/address/0x8cd6e29d3686d24d3c2018cee54621ea0f89313b

**Comment by xbc-main** [comment]
done
