### ISSUE TITLE
Add PGO token logo and info

### ISSUE THREAD

**Issue by pokemongo999** [kswap-finance/static#32]
## Smart Contract Address
0x60fa9b096E1142Bf360628De03d6B3603C1D10f7

## Logo Link
https://pgo.farm/pgo.png
https://pgo.farm/pgo-logo.jpg

## Audit Report Link
https://attest.im/attestation/searchResult?qurey=a611bda17d9d425ea29a7f858803f6f7

## Liquidity Pool Supply with TVL More Than 200,000 USDT
0x7a23255ef4a300c46f17abe31302be1838a8c796

**Comment by xbc-main** [comment]
done
