### ISSUE TITLE
Add OKmoon, please help

### ISSUE THREAD

**Issue by OKMoon-SLStars** [kswap-finance/static#7]
## Smart Contract Address
Contract address ：0xbb25d219cbf8963ec9b8d4e01361fb529e49263e

## Logo Link
Logo：https://okmoon.app/img/logo.png

## Audit Report Link
v0.01

## PS
Our token trading volume has ranked eighth on Kswap, and we have built the SLStars Metaverse game (test). We hope that KSWAP will provide a suggestion to join the list. Thank you for your review.
website:  https://okmoon.app/

**Comment by OKMoon-SLStars** [comment]
Thank you for checking, can you provide us with constructive solutions, such as: define another name or other in KSWAP

**Comment by xbc-main** [comment]
change name and supply audit report

**Comment by OKMoon-SLStars** [comment]
> change name and supply audit report

Can it be defined as a name without ok in kswap？
