### ISSUE TITLE
添加Flux代币白名单

### ISSUE THREAD

**Issue by 3013143008** [kswap-finance/static#8]
Smart Contract Address
FLUXK(OEC)	0xd0C6821aba4FCC65e8f1542589e64BAe9dE11228
 
Logo Link：https://www.figma.com/file/utk3iKk76N0szIGMx3z2GL/flux-logo-for-wallets?node-id=0%3A1

Audit Report Link：Certik审计报告地址：https://certik.org/projects/flux

**Comment by xbc-main** [comment]
done
